use_frameworks!

target 'LLYSDK_Example' do
  pod 'LLYSDK', :path => '../'

  target 'LLYSDK_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
